### ISSUE TITLE
感谢开源

### ISSUE THREAD

**Issue by fslove** [joker-qi/WiscKey#1]
Hi, Qi
感谢你无私的将这个项目开源,我真的很高兴能在KV泛滥的网络里找到这个项目,
目前我正好遇到了一个尴尬的瓶颈,因为是个人非商业用途,没法用大型的FS系统,因为磁盘空间紧张,它们都太脓肿和强大了,.
在这个神奇的2月,我测试了很多开源小型文件储存系统和KV,最后选择了leveldb,并不是它有多好,而是它轻便而且是大厂的不会因为出现奇怪BUG没人管,导致我的数据丢失,
Leveldb在我实际测试中,普通硬盘(7200rpm),写入数据量大概在50G~200G左右,(每个value在10Kb ~ 2Mb)后出现随机的出现CPU 100%(很长时间不能恢复),Leveldb所提供的参数并没有有效的改变这个尴尬的问题.
目前我正在测试rocksdb,目前看来rocksdb还没有出现CPU100%的尴尬问题.
我正打算着手测试你的WiscKey,对于大value你有什么好的调优建议吗?
新春快乐 :)

**Comment by joker-qi** [comment]
适当的增加sst文件的大小，适当的增加write_buffer_size的大小。cpu长时间跑满应该是后台的合并线程再做合并操作，可能是因为合并的文件数太多了吧，而且leveldb不像rocksdb，它只支持一个后台合并线程。对于wisckey的大value的调优，你可以当成是对leveldb的小value的调优场景，需要注意的是wisckey多出的那几个与垃圾回收有关的参数，如果不在乎磁盘浪费，可以设成离线回收的模式。而且我这个肯定是有很多bug的¥_¥，希望不要坑到您

**Comment by Ye-Tian-Zero** [comment]
> Hi, Qi
> 感谢你无私的将这个项目开源,我真的很高兴能在KV泛滥的网络里找到这个项目,
> 目前我正好遇到了一个尴尬的瓶颈,因为是个人非商业用途,没法用大型的FS系统,因为磁盘空间紧张,它们都太脓肿和强大了,.
> 在这个神奇的2月,我测试了很多开源小型文件储存系统和KV,最后选择了leveldb,并不是它有多好,而是它轻便而且是大厂的不会因为出现奇怪BUG没人管,导致我的数据丢失,
> Leveldb在我实际测试中,普通硬盘(7200rpm),写入数据量大概在50G~200G左右,(每个value在10Kb ~ 2Mb)后出现随机的出现CPU 100%(很长时间不能恢复),Leveldb所提供的参数并没有有效的改变这个尴尬的问题.
> 目前我正在测试rocksdb,目前看来rocksdb还没有出现CPU100%的尴尬问题.
> 我正打算着手测试你的WiscKey,对于大value你有什么好的调优建议吗?
> 新春快乐 :)

有试过把sst的block size开大么？
