### ISSUE TITLE
FreeBSD 11 or OS X 11 报错

### ISSUE THREAD

**Issue by fslove** [joker-qi/WiscKey#2]
在BSD内核下gcc和clang都不能正常编译,tr1这个貌似被BSD废掉了,
菜鸟一只,希望有空的时候顺带重视下弱小的BSD群体 T_T.
----------------------------
clang++ (4.0)
clang++-devel(7.0)
-----------------------------

### 

```
root@bsd11-build:~/WiscKey # gmake
clang++-devel -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x  -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_ATOMIC_PR
ESENT -O2 -DNDEBUG -fPIC -c db/db_impl.cc -o out-shared/db/db_impl.o
clang-7.0: warning: argument unused during compilation: '-L/usr/lib' [-Wunused-command-line-argument]
clang-7.0: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
In file included from db/db_impl.cc:5:
In file included from ./db/db_impl.h:19:
./db/vlog_manager.h:35:14: error: no member named 'tr1' in namespace 'std'
        std::tr1::unordered_map<uint64_t, VlogInfo> manager_;
        ~~~~~^
./db/vlog_manager.h:36:14: error: no member named 'tr1' in namespace 'std'
        std::tr1::unordered_set<uint64_t> cleaning_vlog_set_;
        ~~~~~^
db/db_impl.cc:143:30: error: no member named 'clean_threshold' in 'leveldb::Options'
      vlog_manager_(options_.clean_threshold),
                    ~~~~~~~~ ^
db/db_impl.cc:969:30: error: no member named 'log_dropCount_threshold' in 'leveldb::Options'
  if(drop_count_ >= options_.log_dropCount_threshold)
                    ~~~~~~~~ ^
db/db_impl.cc:1360:14: error: cannot initialize object parameter of type 'leveldb::DB' with an expression of type 'leveldb::DBImpl'
  return DB::Put(o, key, val);
             ^~~
db/db_impl.cc:1364:14: error: cannot initialize object parameter of type 'leveldb::DB' with an expression of type 'leveldb::DBImpl'
  return DB::Delete(options, key);
             ^~~~~~
db/db_impl.cc:1498:33: error: no member named 'max_vlog_size' in 'leveldb::Options'; did you mean 'max_file_size'?
      if(vlog_head_ >= options_.max_vlog_size)
                                ^~~~~~~~~~~~~
                                max_file_size
/usr/local/include/leveldb/options.h:125:10: note: 'max_file_size' declared here
  size_t max_file_size;
         ^
db/db_impl.cc:1650:71: error: no member named 'min_clean_threshold' in 'leveldb::Options'
    std::set<uint64_t> vlogs = vlog_manager_.GetVlogsToClean(options_.min_clean_threshold);
                                                             ~~~~~~~~ ^
db/db_impl.cc:1867:14: error: assigning to 'leveldb::DB *' from incompatible type 'leveldb::DBImpl *'
    *dbptr = impl;
             ^~~~
9 errors generated.
gmake: *** [Makefile:419: out-shared/db/db_impl.o] Error 1
root@bsd11-build:~/WiscKey #
```

------------------------------------
FALLOC_FL_PUNCH_HOLE //可能需要手动定义
g++6
g++7
g++8
--------------------------------------
### ```

- root@bsd11-build:~/WiscKey # gmake
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/db_impl.cc -o out-shared/db/db_impl.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/db_iter.cc -o out-shared/db/db_iter.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/dbformat.cc -o out-shared/db/dbformat.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/dumpfile.cc -o out-shared/db/dumpfile.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/filename.cc -o out-shared/db/filename.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/garbage_collector.cc -o out-shared/db/garbage_collector.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/log_reader.cc -o out-shared/db/log_reader.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/log_writer.cc -o out-shared/db/log_writer.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/memtable.cc -o out-shared/db/memtable.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/repair.cc -o out-shared/db/repair.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/table_cache.cc -o out-shared/db/table_cache.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/version_edit.cc -o out-shared/db/version_edit.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/version_set.cc -o out-shared/db/version_set.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/vlog_manager.cc -o out-shared/db/vlog_manager.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/vlog_reader.cc -o out-shared/db/vlog_reader.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/vlog_writer.cc -o out-shared/db/vlog_writer.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c db/write_batch.cc -o out-shared/db/write_batch.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c table/block.cc -o out-shared/table/block.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c table/block_builder.cc -o out-shared/table/block_builder.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c table/filter_block.cc -o out-shared/table/filter_block.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c table/format.cc -o out-shared/table/format.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c table/iterator.cc -o out-shared/table/iterator.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c table/merger.cc -o out-shared/table/merger.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c table/table.cc -o out-shared/table/table.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c table/table_builder.cc -o out-shared/table/table_builder.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c table/two_level_iterator.cc -o out-shared/table/two_level_iterator.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c util/arena.cc -o out-shared/util/arena.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c util/bloom.cc -o out-shared/util/bloom.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c util/cache.cc -o out-shared/util/cache.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c util/coding.cc -o out-shared/util/coding.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c util/comparator.cc -o out-shared/util/comparator.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c util/crc32c.cc -o out-shared/util/crc32c.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c util/env.cc -o out-shared/util/env.o
- g++ -I. -I/usr/include -I/usr/local/include -L/usr/lib -L/usr/local/lib -I./include -std=c++0x -fno-builtin-memcmp -D_REENTRANT -DOS_FREEBSD -DLEVELDB_PLATFORM_POSIX -DLEVELDB_
- ATOMIC_PRESENT -O2 -DNDEBUG -fPIC -c util/env_posix.cc -o out-shared/util/env_posix.o
- util/env_posix.cc: In member function 'virtual leveldb::Status leveldb::{anonymous}::PosixSequentialFile::DeallocateDiskSpace(uint64_t, size_t)':
- util/env_posix.cc:137:34: error: 'FALLOC_FL_PUNCH_HOLE' was not declared in this scope
-        if(fallocate(fileno(file_),FALLOC_FL_PUNCH_HOLE|FALLOC_FL_KEEP_SIZE, offset, len)<0)
-                                   ^~~~~~~~~~~~~~~~~~~~
- util/env_posix.cc:137:55: error: 'FALLOC_FL_KEEP_SIZE' was not declared in this scope
-        if(fallocate(fileno(file_),FALLOC_FL_PUNCH_HOLE|FALLOC_FL_KEEP_SIZE, offset, len)<0)
-                                                        ^~~~~~~~~~~~~~~~~~~
- util/env_posix.cc:137:87: error: 'fallocate' was not declared in this scope
-        if(fallocate(fileno(file_),FALLOC_FL_PUNCH_HOLE|FALLOC_FL_KEEP_SIZE, offset, len)<0)
-                                                                                        ^
- gmake: *** [Makefile:419: out-shared/util/env_posix.o] Error 1
- root@bsd11-build:~/WiscKey #

```

**Comment by joker-qi** [comment]
因为leveldb是c++98的风格，所以unordered开头的容器都加上了tr1，要不你试试去掉tr1，然后修改下makefile，用c++11标准编编试试。你可以把fallocate那句注释掉，只不过会造成不能立刻释放掉磁盘文件已经失效的数据所占的磁盘空间，当然最后整个文件删除时还是能确保磁盘空间的释放。放假回家手头没有电脑，可能需要等几天才能回复您，我也是菜鸟一枚

**Comment by fslove** [comment]
没事儿,等您空闲了再说啦.
我想问下,WiscKey有没有现成的API去get_key,用于查重,DB->Get还得丢掉

**Comment by joker-qi** [comment]
wiskey的api基本与leveldb一样，只不过少了支持快照的api，多了个手动垃圾回收的api，你说的查重是什么意思，Get还得丢掉，没太懂你您什么意思

**Comment by fslove** [comment]
目前查询重复的key唯一可用的就是DB->Get,但是DB->Get会返回value,其实我只需要知道这个key是否存在,不知道WiscKey可否增加个只查询key是否存在的API.

**Comment by joker-qi** [comment]
不存在，但这个接口可以加，加起来很简单，对于leveldb这个接口的确没啥意义，对wisckey这个接口还是有意义的

**Comment by joker-qi** [comment]
你加我qq把，708913847
