### ISSUE TITLE
请问目前该数据库有应用到线上环境么？

### ISSUE THREAD

**Issue by chang290** [joker-qi/WiscKey#5]
我们公司目前使用rocksdb作为底层存储引擎，compaction对性能影响较为显著，正在想办法解决该问题，看到该项目。有什么方法能方便沟通么？

**Comment by joker-qi** [comment]
不好意思呢，这只是我写的一个毕业设计，没有用到线上，未知bug可能还很多，而且是基于leveldb的，没有rocksdb那么强大，我觉得compaction优化可以用kv分离加速compaction，但会牺牲读性能，不一定效果很好；还有就是尽量让写入到level0层的文件key的范围不要跨度太大，类似于顺序写的好处一样，但这个好像比较难做到。
