### ISSUE TITLE
Test VlogTest.Read error

### ISSUE THREAD

**Issue by raoxiaoman** [joker-qi/WiscKey#6]
作者，你好！
我最近也在阅读wisckey的论文，没找到该实验室的代码，在github找了下就找到你的了，就想研究学习下，但是我跑了几个版本的vlogTest，c_test，dbench,发现都不能全过，都会错在Read方法中，这是bug吗？

==== Test VlogTest.Read
db/vlog_test.cc:265: Assertion failure reader_->Read(buf, initial_offset_record_sizes_[expected_record_offset], pos)

db_bench: db/db_impl.cc:1293: leveldb::Status leveldb::DBImpl::RealValue(leveldb::Slice, std::__cxx11::string*): Assertion `b' failed.
[1]    7137 abort (core dumped)  ./db_bench

**Comment by joker-qi** [comment]
最近一直忙着复习找工作就没咋管过这个，不好意思哈，db_bench我记得是可以跑的啊，vlog_test可能后面改的时候没有修改测试文件，我这个不是按他论文改的。
